
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { createContext } from 'react'
import  Theme  from './components/Theme'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className="scroll-smooth">
        < Theme>
      <body className={inter.className}>{children}</body>
      </Theme>
    </html>
  )
}
